package com.sun.pojo;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.UID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.MONEY
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ID
     *
     * @return the value of account.ID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ID
     *
     * @param id the value for account.ID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.UID
     *
     * @return the value of account.UID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.UID
     *
     * @param uid the value for account.UID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.MONEY
     *
     * @return the value of account.MONEY
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.MONEY
     *
     * @param money the value for account.MONEY
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}