package com.sun.pojo;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_NAME
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_DESC
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    private String roleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_NAME
     *
     * @return the value of role.ROLE_NAME
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_NAME
     *
     * @param roleName the value for role.ROLE_NAME
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_DESC
     *
     * @return the value of role.ROLE_DESC
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_DESC
     *
     * @param roleDesc the value for role.ROLE_DESC
     *
     * @mbggenerated Thu Aug 05 22:22:22 CST 2021
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }
}